version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: kanastra_db
      POSTGRES_USER: kanastra_user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432" # Map port 5432 on the host to port 5432 in the container

  web:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend:latest
    ports:
      - "8000:8000"
    environment:
      DB_NAME: kanastra_db
      DB_USER: kanastra_user
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432

  frontend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:latest
    ports:
      - "3000:3000"
    networks:
      - kanastra-network

networks:
  kanastra-network:
    driver: bridge
