name: Build and Deploy

on:
  push:
    branches:
      - staging

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to directory with Dockerfile
        run: cd backend

      - name: Build Docker image
        run: docker build -t my_django_app .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name my_django_container my_django_app
